language: elixir

elixir:
  - 1.6
  - 1.5
otp_release:
  - 20.2
  - 20.0

matrix:
  exclude:
    - elixir: 1.3
      otp_release: 19.3
    - elixir: 1.3
      otp_release: 20.0
    - elixir: 1.3
      otp_release: 20.2
    - elixir: 1.6
      otp_release: 19.3

sudo: false